
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12.8"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=particle_swarm --cov-report=xml
        # Replace 'my_package' with your actual package name

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tuckluck/Particle_Swarm_Algo
